
use_directory_urls: false

site_name: "Documentazione Super Progetto"
site_author: "Mario Rossi"
docs_dir: '../../docs/en'                           # Where to find the English markdown files
site_dir: '../../generated/en'                      # Where to put the English HTML files

theme:
  name: material


nav:
- "<span class='ms-Icon ms-Icon--WaitlistConfirm'></span> Installazione e deploy": /Getting started.html
- "<span class='ms-Icon ms-Icon--AuthenticatorApp'></span> Authentication": /Authentication.html
- "<span class='ms-Icon ms-Icon--ModelingView'></span> Tenant Management": /Gestione Tenant.html
- "<span class='ms-Icon ms-Icon--Admin'></span> Administration": /Administration.html
- "<span class='ms-Icon ms-Icon--ViewDashboard'></span> Dashboard": /Dashboard.html
- "<span class='ms-Icon ms-Icon--OpenFolderHorizontal'></span> Inventory": /Inventory.html
- "<span class='ms-Icon ms-Icon--AreaChart'></span> Monitoring": /Monitoring.html
- "<span class='ms-Icon ms-Icon--AzureKeyVault'></span> Security": /Security.html
- "<span class='ms-Icon ms-Icon--AddToShoppingList'></span> Catalog": /Catalog.html
- "<span class='ms-Icon ms-Icon--Money'></span> Costs & Usage": /Costs e Usage.html
- "<span class='ms-Icon ms-Icon--BranchFork2'></span> Provisioning": /Provisioning.html
- "<span class='ms-Icon ms-Icon--Lifesaver'></span> Backup & Disaster Recovery": /Backup Disaster Recovery.html
- "<span class='ms-Icon ms-Icon--SecondaryNav'></span> Shared Features": /Funzionalità condivise.html
- "<span class='ms-Icon ms-Icon--ReservationOrders'></span> Service Detail Design": /Service Detail Design.html
- "<span class='ms-Icon ms-Icon--AzureAPIManagement'></span> REST API":
  - "Finops": finopsAPI.html
  - "Provisioning": provisioningAPI.html
  - "Resource Manager": rmAPI.html
  - "Abstraction Layer": absAPI.html
  - "Report Manager": rmreportAPI.html
  - "Cost": rmcostsAPI.html
  - "Monitoring": rmmonitoringAPI.html
  - "Security": rmsecurityAPI.html
  - "Services": rmserviceAPI.html
  - "SIEM": siemAPI.html
  - "Taxonomy Manager": txmAPI.html
  - "Tenant Manager": tenantAPI.html
  - "Orchestrator": orchestratorAPI.html
  - "Service detail design": api.html
- "<span class='ms-Icon ms-Icon--PDF'></span> Versione PDF completa": SCMP_SUM.pdf


# Configuration
theme:
  name: material
  custom_dir: '../../overrides/'                  # This is where the customization of the theme lives  
  logo: personalization/logo.png
  language: en 

extra_css:
  - overrides/personalization/eng-standard-theme.css
  - overrides/personalization/toc.css
  - overrides/personalization/fabric.min.css

extra_javascript:
  - overrides/personalization/toc.js
  - overrides/personalization/script.js

# Customization
extra:
  version:
    provider: mike
  navigation:
    collapse: true
  media_dir: 'images/media'
  alternate:  

      # Switch to English
    - name: English
      link: /en/
      lang: en

    # Switch to Dutch
    - name: Italiano
      link: /it/
      lang: it

plugins:
- search 
- render_swagger:
    css: personalization/swagger-ui.css
- print-site

markdown_extensions:
  - markdown_captions
  - admonition
  - pymdownx.details
  - pymdownx.superfences