backend:
  name: github
  repo: TUO-USER/TUA-REPO
  branch: main

media_folder: "docs/assets"
public_folder: "/assets"

collections:
- name: "docs"
  label: "Documentazione"
  folder: "docs"
  create: true
  slug: "{{slug}}"
  fields:
  - { name: "title", label: "Titolo", widget: "string" }
  - { name: "body", label: "Contenuto", widget: "markdown" }
